services: 
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile 
    ports: 
      - "8000:8000"
    env_file: .env
    depends_on: 
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on: 
      - backend 
  db: 
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWOD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: {}
